#!/bin/bash

# Run Proot login script and execute Nexus script inside the PRoot session
curl -sSL "https://raw.githubusercontent.com/Crypto-Crood/my-tac-app/refs/heads/main/Proot%20login" | bash

# Wait for Proot setup to complete
sleep 5

# Execute the Nexus script inside the Proot session
proot-distro login ubuntu -- bash -c "curl -sSL 'https://raw.githubusercontent.com/Crypto-Crood/my-tac-app/refs/heads/main/Nexus%20script' | bash"
