#!/bin/bash

# Install Rust if not already installed
rustc --version || curl https://sh.rustup.rs -sSf | sh -s -- -y

# Define variables
NEXUS_HOME=$HOME/.nexus
GREEN='\033[1;32m'
ORANGE='\033[1;33m'
NC='\033[0m' # No Color

# Ensure Nexus home directory exists
mkdir -p $NEXUS_HOME

# Ensure Git is installed
if ! command -v git &>/dev/null; then
  echo "Git is not installed. Installing Git..."
  apt update && apt install -y git
fi

# Check for existing Prover ID
PROVER_ID=$(cat $NEXUS_HOME/prover-id 2>/dev/null)
if [ "${#PROVER_ID}" -ne "28" ]; then
    echo -e "\n${ORANGE}The Nexus network is currently in devnet. It is important to note that you cannot earn Nexus points.${NC}"
    echo -e "\nInstead, devnet allows developers to experiment and build with the network. Stay tuned for updates regarding future testnets.\n"
fi

# Clone or update the Nexus repository
REPO_PATH=$NEXUS_HOME/network-api
if [ -d "$REPO_PATH" ]; then
  echo "$REPO_PATH exists. Updating..."
  (cd $REPO_PATH && git stash save --quiet && git fetch --tags)
else
  (cd $NEXUS_HOME && git clone https://github.com/nexus-xyz/network-api)
fi

# Checkout latest tag
(cd $REPO_PATH && git -c advice.detachedHead=false checkout $(git rev-list --tags --max-count=1))

# Run the Nexus CLI without prompts
(cd $REPO_PATH/clients/cli && cargo run --release --bin prover -- beta.orchestrator.nexus.xyz)
